### ISSUE TITLE
Archive this feedstock

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/libmagic-feedstock#14]
@conda-forge/core Please can someone archive this feedstock.

This feedstock was a duplicate of `file`. I've merged them into a single multi-output feedstock in https://github.com/conda-forge/file-feedstock/pull/2 where the contents of each better reflects it's name (`bin/file` comes from `file` and `lib/libmagic.so` comes from `libmagic`). The members of both feedstock teams agreed to the change in the aforementioned PR.

**Comment by xhochy** [comment]
Archiving.
